version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        Cluster: ECS-Cluster-FlaskApp
        TaskDefinition: arn:aws:ecs:us-east-1:433337163311:task-definition/TaskDefinatioECS-Service:2
        LaunchType: FARGATE
        ServiceName: ECS-Service
        SchedulingStrategy: REPLICA
        DesiredCount: 2
        LoadBalancerInfo:
        - ContainerName: flaskapp
          ContainerPort: 80
          TargetGroupArn:
            Ref: TargetGroup
        NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
          - Ref: SecurityGroup
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2