AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for ECS Blue-Green Deployment

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 1
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 2
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Private Subnet 1
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Private Subnet 2

Resources:
  ALBLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ALB-ECS-Service
      Scheme: internet-facing
      Type: application
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALBLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref BlueTargetGroup

  BlueTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: ECS-Blue-TG
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId

  GreenTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: ECS-Green-TG
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId

  ECSBlueGreenDeployment:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: ECSDeploymentGroup
      DeploymentConfigName: CodeDeployDefault.ECSLinear10PercentEvery1Minutes
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      BlueGreenDeploymentConfiguration:
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
        GreenFleetProvisioningOption:
          Action: COPY_AUTO_SCALING_GROUP
        TerminationWaitTimeInMinutes: 5
      LoadBalancerInfo:
        TargetGroupInfoList:
          - Name: BlueTargetGroup
            TargetGroup: !Ref BlueTargetGroup
          - Name: GreenTargetGroup
            TargetGroup: !Ref GreenTargetGroup
      Deployment:
        Description: Blue-Green Deployment for ECS Service
        IgnoreApplicationStopFailures: false

  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: CodeDeployServiceRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:DescribeServices
                  - ecs:UpdateService
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecs:ListClusters
                  - ecs:DescribeClusters
                  - autoscaling:DescribeAutoScalingGroups
                Resource: "*"

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: ECSDeploymentApp
      ComputePlatform: ECS
